service: iandaley-dot-ninja

provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  region: us-east-1
  environment:
    MONGO_URI: ${self:custom.environment.MONGO_URI}
    # MONGO_PROD_URI: ${self:custom.environment.MONGO_URI}

plugins:
  - serverless-nextjs-plugin
  - serverless-domain-manager

custom:
  name: iandaley-dot-ninja
  stage: ${opt:stage, self:provider.stage}
  serverless-nextjs: # <- add here
    assetsBucketName: 'iandaley-dot-ninja-static-assets-${self:provider.stage}'
  customDomain: # <- add here
    domainName: '${self:provider.stage}.iandaley.ninja'
    certificateName: '*.iandaley.ninja'
    basePath: ''
    stage: ${self:provider.stage}
    createRoute53Record: true

package: # <- add here
  # exclude everything
  # page handlers are automatically included by the plugin
  exclude:
    - ./**
